const server = {}
const karyawan = require('./admin/karyawan')
const admin = require('./admin/admin')
const kriteria = require('./admin/kriteria')
const statusPenilaian = require('./admin/statusPenilaian')
const generate = require('./admin/generate')
const penilaian = require('./karyawan/penilaian')
const akunKaryawan = require('./karyawan/akun')
const akumulasi = require('./admin/akumulasi')
const terbaik = require('./admin/terbaik')
const profile = require('./admin/profile')
const profileKaryawan = require('./karyawan/profile')
const pegawaiTerbaik = require('./karyawan/kepala biro/terbaik')
const laporan = require('./karyawan/kepala biro/laporan')
const dashboard = require('./admin/dashboard')
const pegawaiTerburuk = require('./admin/terburuk')
const terburukBiro = require('./karyawan/kepala biro/terburuk')
const profileBiro = require('./karyawan/kepala biro/profile')
const penilaianKabag = require('./karyawan/kepala bagian/penilaian')
const profileKabag = require('./karyawan/kepala bagian/profile')
const historyPenilaianKabag = require('./karyawan/kepala bagian/riwayat')
const view = require('./viewWeb/view')

server.karyawan = karyawan
server.admin = admin
server.kriteria = kriteria
server.statusPenilaian = statusPenilaian
server.generate = generate
server.penilaian = penilaian
server.akunKaryawan = akunKaryawan
server.akumulasi = akumulasi
server.terbaik = terbaik
server.profile = profile
server.profileKaryawan = profileKaryawan
server.pegawaiTerbaik = pegawaiTerbaik
server.laporan = laporan
server.dashboard = dashboard
server.pegawaiTerburuk = pegawaiTerburuk
server.terburukBiro = terburukBiro
server.profileBiro = profileBiro
server.penilaianKabag = penilaianKabag
server.profileKabag = profileKabag
server.historyPenilaianKabag = historyPenilaianKabag
server.view = view

module.exports = server