const express = require('express')
const router = express.Router()
const controller = require('../../controllers/viewsWeb/views')
const middleware = require('../../middleware/authentication')

router.get('/loginAdmin', controller.viewsLoginAdmin)
router.get('/dashboardAdmin',middleware.verifyTokenAdmin, controller.viewsDashboard)
router.get('/penilaian',middleware.verifyTokenAdmin, controller.viewsPenilaian)
router.get('/pegawai',middleware.verifyTokenAdmin, controller.viewsKaryawan)
router.get('/generatepegawai',middleware.verifyTokenAdmin, controller.viewsGenerateKaryawan)
router.get('/statusPenilaian',middleware.verifyTokenAdmin, controller.tampilStatus)
router.get('/akumulasiHasil',middleware.verifyTokenAdmin, controller.viewsAkumulasiHasil)
router.get('/pegawaiTerbaikViews',middleware.verifyTokenAdmin, controller.viewsKaryawanTerbaik)
router.get('/profile',middleware.verifyTokenAdmin, controller.viewsProfile)
router.get('/forgotPass', controller.viewsForgotPass)
router.get('/changePass', controller.viewsChangePass)
router.get('/pegawaiTerburukViews',middleware.verifyTokenAdmin, controller.viewsKaryawanTerburuk)
router.get('/', controller.viewsBiorasi)
router.get('/loginKabir', controller.viewsLoginKabir)
router.get('/dashboardKabir',middleware.verifyTokenKepala, controller.viewsDashboardKabir)
router.get('/pelaporanKabir',middleware.verifyTokenKepala, controller.viewsPelaporanKabir)
router.get('/pegawaiTerbaikViewsKabir',middleware.verifyTokenKepala, controller.viewsPegawaiTerbaikKabir)
router.get('/pegawaiTerburukViewsKabir',middleware.verifyTokenKepala, controller.viewsPegawaiTerburukKabir)
router.get('/profileKabir',middleware.verifyTokenKepala, controller.viewsProfileKabir)
router.get('/loginKabag', controller.viewsLoginKabag)
router.get('/dashboardKabag',middleware.verifyTokenKabag, controller.viewsDashboardKabag)
router.get('/penilaianKabag',middleware.verifyTokenKabag, controller.viewsPenilaianKabag)
router.get('/riwayatAkumulasiKabag',middleware.verifyTokenKabag, controller.viewsRiwayatAkumulasiKabag)
router.get('/formPenilaianKabag',middleware.verifyTokenKabag, controller.viewsFormPenilaianKabag)
router.get('/loginPegawai', controller.viewsLoginPegawai)
router.get('/homePegawai',middleware.verifyTokenKaryawan, controller.viewsHomePegawai)
router.get('/profilePegawai',middleware.verifyTokenKaryawan, controller.viewsProfileKaryawan)
router.get('/formPenilaianPegawai',middleware.verifyTokenKaryawan, controller.viewsFormPenilaianPegawai)
router.get('/profileKabag',middleware.verifyTokenKabag, controller.viewsProfileKabag)

module.exports = router